### ISSUE TITLE
Wishlist:  Keyboard friendly input components

### ISSUE THREAD

**Issue by teug91** [dhis2/ui-core#141]
It is not possible to tab to a select field, radio, checkbox, or switch. Navigating with enter and arrow keys within a select field would also be a nice feature.

**Comment by varl** [comment]
Absolutely! This is on the feature list. 👍

**Comment by varl** [comment]
@teug91 is this still a problem in v2?

**Comment by teug91** [comment]
@varl 

The main issue is that you cannot use enter to toggle a switch/radio/checkbox or tab to them. The select field can be controlled using the keyboard, but there is an issue with the label (see #216).

Repo I made for testing:
https://github.com/teug91/test-app

**Comment by varl** [comment]
Thanks @teug91, will take a look.

**Comment by Mohammer5** [comment]
I just created a test story locally to check this, here's what I noticed:

### 1. SelectField (filled & outlined)

* The "focused" state isn't indicated
* It's still focused, so entering a value with the keyboard will select a value
* Hitting "enter" while the SelectField has focus will open the dropdown

### 2. InputField (filled & outlined)

* Works as expected 
  * Displays the focused state

### 3. Radio & Checkbox

* Doesn't handle focus at all (no keyboard events possible)

### 4. Checkbox

* The value of the event passed to the `onChange` callback is `on`/`off`, not the value passed to the `Checkbox` component

## Conclusion

1. The `SelectField` should be relatively easy to fix as it uses the same wrapper as the `InputField`
2. The `Checkbox` and `Radio` component need to be fixed to handle the focus event

Branch that I tested on is: `form_stories`
