### ISSUE TITLE
UI widgets (Headerbar) should respect configured DHIS2_BASE_URL

### ISSUE THREAD

**Issue by amcgee** [dhis2/ui-core#168]
See this example with errors in [Dashboard on Netlify](https://deploy-preview-263--dhis2-dashboards.netlify.com/) with BASE_URL configured to point to `play.dhis2.org/dev`:

<img width="1792" alt="Screenshot 2019-03-18 11 16 05" src="https://user-images.githubusercontent.com/947888/54523316-87336280-496f-11e9-8913-615d7178cc6b.png">

**Comment by varl** [comment]
The HeaderBar now lives in `ui-widgets` and uses the DataProvider pattern so I think we can remove the `BASE_URL` problems from the component entirely.
