### ISSUE TITLE
Background for determinate linear progress/loader

### ISSUE THREAD

**Issue by cooper-joe** [dhis2/ui-core#238]
I think the linear determinate loader/progress would communicate more clearly with a defined background that shows the 'track' of the loader/progress bar. It would then be clearer how much is left to load. I don't think linear loaders will always be used as 100% width of the parent, so this background track becomes necessary. Mockups use `background: rgba(110,122,138,0.20);`, and you can see examples of the mockups [here](https://github.com/dhis2/design-system/blob/master/atoms/loading.md)

**Comment by varl** [comment]
@cooper-joe So we don't actually need a indeterminate linear progress indicator?

**Comment by cooper-joe** [comment]
No, I don't think so. See: https://github.com/dhis2/ui-core/issues/236

**Comment by varl** [comment]
Oh, nice. I missed that one.
