### ISSUE TITLE
Menu item :active/click state

### ISSUE THREAD

**Issue by cooper-joe** [dhis2/ui-core#239]
I think the menu items should have an 'active' clicked state. (See [this mockup of an item selector](https://codepen.io/j_cpr/live/73918a10a96df4de0acaeec4e023edcf), using my intended active state on click).

I was going to add this with `li:active {background-color:grey-400};` on the menu item component, but I noticed that there is already an `li.active` class set. Adjusting this `.active` class didn't have any effect when clicking on a menu item. I didn't want to add the `:active` pseudo-class as I was unsure how clicks were being handled here, especially regarding child sub-menus. Adding `:active` seemed to change the background color for the parent items when clicking a child. Advice appreciated!

**Comment by Mohammer5** [comment]
@cooper-joe I just added the `active` class to one of the menu items in the dev tools, it just worked fine for me:

![image](https://user-images.githubusercontent.com/10101831/58543334-92243200-81ff-11e9-93c0-79f086872bb5.png)

If you want to know how to do that with the react component, it just needs the attribute `active`:

```jsx
<MenuItem active ... />
```

**Comment by cooper-joe** [comment]
@Mohammer5 I see, but that `active` class is not actually being applied when the user clicks on the menu-item itself? Is there a way to enable that? I'm not sure where/when the active class is actually being used actually.

**Comment by Mohammer5** [comment]
No, the stories are static, which means there's no way of interacting with them. I've discussed that with @varl. After having worked with storybook for a while now, I came to the conclusion that it makes sense to keep state our of the storybook (stateful stories have a few drawbacks).
A story is basically a scenario for a particular state (at least in `ui-core`).

These "building blocks" will be used to create widgets, forms, etc. They will have stories which will be interactive in nature (once we have the `ui-forms` library, form stories will be interactive), where you'll be able to see how our components in `ui-core` behave.

**Comment by cooper-joe** [comment]
Ah, that makes sense. Thanks for clearing that up. I'll make adjustments to the `active` class.

**Comment by varl** [comment]
As an aside I've been looking into adding the ability to change props within Storybook, something like [Knobs](https://storybooks-official.netlify.com/?path=/story/addons-knobs-withknobs--optionsknob).

**Comment by Mohammer5** [comment]
@varl That looks pretty neat! Won't solve all problems though, it's not the same as interacting with the component itself. Did you have a look at this one already? https://github.com/Sambego/storybook-state

**Comment by varl** [comment]
No, will do. :+1:
