### ISSUE TITLE
Add active state bg color to MenuItem - using pseudo element

### ISSUE THREAD

**Issue by jenniferarnesen** [dhis2/ui-core#243]
A background color for Menu Item with class `active` was implemented here:  https://github.com/dhis2/ui-core/pull/240

However, this is not having any effect when I use the component in dashboards. When I added css for the pseudoelement:

```li:active {background-color: ${colors.grey400};}``` then I get the desired effect.

Could you add this as an additional css style?

**Comment by varl** [comment]
I think the intention was that the `.active` class has to be added manually. 🤔

Not entirely sure why. Doesn't look like the `:focus` state would interfere with that.

**Comment by varl** [comment]
`.active` and `:active` represent different things, checking with @cooper-joe if they can use the same colours or need to be distinct.

### Current behaviour makes it hard to know if an item has been clicked:

![menu-interaction-current](https://user-images.githubusercontent.com/185449/58968198-ee65f380-87b5-11e9-9adf-4fff0a01fa19.gif)

### Using `.active` to show that many items have been selected:

![image](https://user-images.githubusercontent.com/185449/58968128-cc6c7100-87b5-11e9-8403-3ab524a8431f.png)

### Using `:active` to indicate that an element has been interacted with:

![menu-interaction-pseudo](https://user-images.githubusercontent.com/185449/58968173-df7f4100-87b5-11e9-8fac-b132d7639748.gif)
