### ISSUE TITLE
Rework text input (replace outlined style)

### ISSUE THREAD

**Issue by cooper-joe** [dhis2/ui-core#306]
I made a mistake with the input fields. I was writing the documentation for filled/outlined styles and I realised I couldn’t really justify where one would be used over the other. I made the mistake of taking this from Material Design without doing due dilligence. 

To rectify this, I would like to replace the 'outlined' style with a regular, traditional, split label+input style. The 'filled' style can remain unchanged.

To be clear, the input types we would then have:
- filled
- traditional split (separate? Lacking a good name)

Apologies that this will undo some work already done to a high standard. I spoke to @varl and he thought we might be able to make these changes to the outlined style without making breaking changes. I think it may be possible, all the states remain the same functionally (error, disabled, dense etc.), it is visually that there are big changes. Ideally I would like to make this change soon, before apps start using the outlined style extensively.

Please grab me on slack to discuss if needed. Here are the specs: https://sketch.cloud/s/DwkDk/a/jO5k5b

CSS for the input box-shadow, for easy copy&paste:
```css
box-shadow: inset 0 0 0 1px rgba(102,113,123,0.25), inset 0 1px 2px 0 rgba(102,113,123,0.21);
```

**Comment by Mohammer5** [comment]
> I spoke to @varl and he thought we might be able to make these changes to the outlined style without making breaking changes

I'm 100% sure that we'll be able to change it without changing the component's api.

> Here are the specs: https://sketch.cloud/s/DwkDk/a/jO5k5b

I like this one a lot more tbh! Looks neat

**Comment by cooper-joe** [comment]
@Mohammer5 Sounds good! As I wrote above, the different states shouldn't require major changes; error still has the icon, help text still appears below, etc. The disabled state has a little bit different style, but that's it I think. The major change is the label position, and the separation of the label/placeholder (although I believe this is done in the current one already, as label and placeholder can be different?)

Let me know if you have any questions underway 👍

**Comment by cooper-joe** [comment]
A note to say that this rework would also include the 'outlined' select style too.

**Comment by Mohammer5** [comment]
@cooper-joe The help & error texts have a different font size than the label, placeholder and value texts.
What values should I use? In my branch I'm using 16px for label, placeholder and value right now.

**Comment by cooper-joe** [comment]
> @cooper-joe The help & error texts have a different font size than the label, placeholder and value texts.
> What values should I use? In my branch I'm using 16px for label, placeholder and value right now.

@Mohammer5 The specs are here, do they contain the info you're looking for?: https://sketch.cloud/s/DwkDk/a/jO5k5b

For clarity, the sizes and colors are:
Label: 14px, grey900
Placeholder: 14px, grey600
Value: 14px, grey900
Help: 12px, grey700
Error: 12px, red700

**Comment by Mohammer5** [comment]
@cooper-joe Thanks, the specs define the font size of the help and error text as 14px.

> For clarity, the sizes and colors are:
> Label: 14px, grey900
> Placeholder: 14px, grey600
> Value: 14px, grey900
> Help: 12px, grey700
> Error: 12px, red700

12px, that's what I needed to know, cheers

**Comment by cooper-joe** [comment]
@Mohammer5 Ah crap, sorry. My bad, that was meant to define the color only.

**Comment by HendrikThePendric** [comment]
@cooper-joe: sorry I am so late to comment on this issue, it slipped of my radar because it was opened on the first day of my holidays...

I've looked at [the updated design specs](https://github.com/dhis2/design-system/blob/master/atoms/inputfield.md) and have noticed that we now have two types of text-inputs that don't only differ in style, but also in behaviour. I'll explain what I mean:
- The filled input is using a "floating label text" mechanism. The result is that most of the time, the placeholder text is not visible (only when the input has focus + no character has been typed yet). As such the placeholder text is not all that relevant and will probably be omitted most of the time.
- The outlined input has a label above the input at all times. This makes the placeholder text much more important, so probably should be included most of the time.

IMO the only difference between filled and outlined should be the appearance. The choice between the two should be a matter of taste. I would not like two inputs to behave differently from one another.

> I was writing the documentation for filled/outlined styles and I realised I couldn’t really justify where one would be used over the other. 

If this was your motivation for introduce these behavioral differences, I would like to ask:
What type of scenario is better served with a floating label, and which scenario is better served with a label on top?

I would really prefer it if both input types either use a floating label mechanism, or a label on top.

**Comment by cooper-joe** [comment]
@HendrikThePendric Thanks for raising concerns about these inputs. Let me explain my thinking behind this system.

> What type of scenario is better served with a floating label, and which scenario is better served with a label on top?

A floating label suits a situation where, due to lack of space, a label would have been otherwise omitted. For example, text fields that have to fit into toolbars or compact UI's (filtering data dimensions in data-visualizer, for example.) Using a `regular` field in these cases means the label will probably be left out to save space. Then a user is unaware what the field is for when it has been filled. So, the `filled` style is a backup style that can help out in these situations.

However, there's a fair dose of post-rationalisation in that! To be quite honest, the filled styles have been inherited from material-ui. The majority of apps that have been built/updated in the last 2 years have used this `filled` input style. My concern was that excluding this field style from `ui-core` would mean that apps would be hesistant to update to `ui-core` without the help of a designer to rework forms and input usage. So, I thought a reasonable compromise would be to include this legacy style in order to make the adoption of `ui-core` smoother and quicker. For transparency, my decision to include both `regular` and `filled` styles is probably 70% this reason, and 30% '`filled` is sometimes useful'.

I should have made these mixed intentions clearer, my apologies. It doesn't feel quite right to include a component style that I wouldn't include otherwise, however it seems like the most pragmatic way to get `ui-core` in use. I would like feedback on this from everyone in @dhis2/team-apps - I know this is perhaps a risky route, but I hoped that defining `regular` as the default style would avoid this. This could be made even clearer in the design documentation.

**Comment by Mohammer5** [comment]
With the current version (I haven't merged your requested changes yet), you can't omit the label,
it's marked as `required`:
https://github.com/dhis2/ui-core/blob/213734d25a38344cd8d1d505656f3efdcadeb37a/src/InputField/index.js#L101

Also using a label in combination with a placeholder doesn't change anything about the size, neither does leaving out the placeholder:
* [With label; no placeholder and no value](https://d2-ci.github.io/ui-core/?path=/story/inputfield-outlined--no-placeholder-no-value)
* [With label and placeholder; no value](https://d2-ci.github.io/ui-core/?path=/story/inputfield-outlined--placeholder-no-value)

<hr />

Initially, when @HendrikThePendric raised the issues with the new design, I thought that there's now a difference in behavior, but after having compared them to the ones in the live storybook, I think they're still identical in terms of behavior:

1. They both always show the label
1. They both show the placeholder as long as the input's value is empty
1. They both take the same vertical space (as long as we define the label to be required, which I think we should)

> The filled input is using a "floating label text" mechanism. The result is that most of the time, **the placeholder text is not visible (only when the input has focus + no character has been typed yet)**. As such the placeholder text is not all that relevant and will probably be omitted most of the time.

According to the specs, this is not true, check the first screenshot on the [input field's design page](https://github.com/dhis2/design-system/blob/master/atoms/inputfield.md#input-field).

> The outlined input has a label above the input at all times. This makes the placeholder text much more important, so probably should be included most of the time.

I can't find an example where this is not the case for the input with the floating label.

**Comment by varl** [comment]
>The filled input is using a "floating label text" mechanism. **The result is that most of the time, the placeholder text is not visible** (only when the input has focus + no character has been typed yet). As such the placeholder text is not all that relevant and will probably be omitted most of the time.

That is incorrect. If the filled input has a label & and a placeholder, the label will "float" and the placeholder will be in the field:

![image](https://user-images.githubusercontent.com/185449/63586342-6962cd00-c5a1-11e9-9309-2ac573be6f2c.png)

"Hold the place" is the placeholder, "Default label" is the label and the field is not selected.

**Comment by HendrikThePendric** [comment]
> That is incorrect. If the filled input has a label & and a placeholder, the label will "float" and the placeholder will be in the field:
Aha yes, I see it now. Apologies, I must have had another implementation in mind, probably very outdated. So you guys are right, the behaviour is in fact identical. 

I still don't like these different styles though. Especially as some of the arguments for using one over the other aren't really valid:
> A floating label suits a situation where, due to lack of space, a label would have been otherwise omitted.
I think they take up the same space [according to the design-system](https://github.com/dhis2/design-system/blob/master/atoms/inputfield.md)

**Comment by Mohammer5** [comment]
PR is ready, waiting for @cooper-joe's decision

**Comment by varl** [comment]
Was this #337?

**Comment by Mohammer5** [comment]
Yes

**Comment by varl** [comment]
Cool
