### ISSUE TITLE
Checkbox and Radio: Add dense style

### ISSUE THREAD

**Issue by cooper-joe** [dhis2/ui-core#420]
The current checkbox and radio atoms are intended for more standalone usage, they are large enough to be easily clickable when used in forms, for example. However, they are too large for complex UI components (such as the org. unit selector). I do still want to use these atoms though, so I think the best way is to add a `dense` style.

The current `svg`s we use for the components are sized at `24px`. `Dense` style would use `16px`. Is it as simple as adjusting the size here?

`Dense` styles for checkbox are required for the org.unit selector and the select components, so this issue blocks those.

**Comment by Mohammer5** [comment]
We can easily adjust SVG's sizes, but if that's a design spec requirement, you should worry about how it's implemented (it'll be quite easy though!)

I'd request there to be specs before working on this though

**Comment by cooper-joe** [comment]
Sounds good! Assigning to myself, will update when the specs are ready.

**Comment by HendrikThePendric** [comment]
Dense mode is available in Radio, Checkbox, and Switch, see #458 and #516. Closing this now.
