### ISSUE TITLE
New status icon position

### ISSUE THREAD

**Issue by HendrikThePendric** [dhis2/ui-core#464]
### Context
Both @ismay and I encountered some problems when implementing Select and TextArea. These problems stem from the fact that in the current design we have visually tried to show the status icon inside of the input. In the actual implementation we have wrapped both the input and the status-icon in a div on which we've defined the border-color etc. Specifically this is causing the following problems:
- For these Input elements we have to keep track of the input elements focus-state in as a component state property. This is adding a little unnecessary overhead to the component.
- In the TextArea we are encountering some problems with the position of the scrollbar, see [this fiddle for illustration](https://jsfiddle.net/hendrikdegraaf/3njh2rpg/8/). This can only be solved by additional logic in the component, making this less lightweight.

### Solution
So, @ismay's suggestion to solve this was to re-implement the design and come up with a solution that doesn't try to make the container div look like an input, but just style the _actual input_ instead.

We first discussed things with @varl and he was on board with trying to solve things this way. We then discussed things with @cooper-joe and presented him with a revised design. Of course he came up with a much better solution, which looks like this:
![new_error_icon styles](https://user-images.githubusercontent.com/353236/65881546-df720500-e393-11e9-8aaf-f31d05481475.png)
This solution doesn't just help the current implementation of the Input/TextArea/Select, but we will also be able to use this for components such as `RadioGroupField` etc.

**UPDATE**
We decided to go with the icon-next-to-input after all (https://github.com/dhis2/ui-core/pull/465#issuecomment-536912958) https://github.com/dhis2/ui-core/pull/465#issuecomment-536917144
![image](https://user-images.githubusercontent.com/353236/65952439-2c141980-e442-11e9-8d1e-357728316ece.png)

### Implementation
To complete this transition the following tasks need to be completed:
- [ ] ~~Add an `icon` prop to the `Help` component~~
- [ ] Update the implementation of `Input` and `InputField`
- [ ] Update the WIP implementation of `Select` and `SelectField`
- [ ] Update the WIP implementation of `TextArea` and `TextAreaField`

**Comment by varl** [comment]
Important information in:

- https://github.com/dhis2/ui-core/pull/465#issuecomment-536912958 (@HendrikThePendric)
- https://github.com/dhis2/ui-core/pull/465#issuecomment-536917144 (@varl)

**Comment by varl** [comment]
@cooper-joe What do you think of these PRs?

- https://github.com/dhis2/ui-core/pull/472
- https://github.com/dhis2/ui-core/pull/456

**Comment by cooper-joe** [comment]
@varl I agree with the conclusions reached about the status icon for the `input` and `textarea`. The chosen solution is the best for simplicity and flexibility.                                                                       

I think it's important now to come up with a semi-consistent way of displaying status for other types, radioGroup, tree, transfer. This could be done with a 'status' component, but will need some thought and discussion. I'll continue that work on another issue, this one that is specific to `input`s I believe can be closed.

**Comment by varl** [comment]
Thanks @cooper-joe.
