### ISSUE TITLE
input 'width' property

### ISSUE THREAD

**Issue by cooper-joe** [dhis2/ui-core#467]
Extracting a task from a discussion taking place here: https://github.com/dhis2/ui-core/pull/456#issuecomment-536497310

`input` components need a property to define the input width. Discussion is ongoing as to how width will be handled for `input` and `inputField`. 

Width has been added to an option in the updated `input` docs, currently a draft PR (https://github.com/dhis2/design-system/pull/12)

**Comment by Mohammer5** [comment]
Once the `next` branch has been merged, we'll expose the `input` component directly, which accepts a className prop, so the width can be set explicitly via css.

But I'm not sure how we could handle this with the `InputField`, there are several options:
* Pass through an `inputClassName` prop
* Except a width prop and create a css rule that will be passed to the internally used `Input`
* Adding a width prop to both the `Input` and `InputField`

Using a prop is the easiest solution and will work well with non-responsive pages. Once we enter the responsiveness-territory this might be a bad solution, so I'm not sure which way to go. I think passing down classNames is the cleanest option, but if we introduce that as a standard, should then all molecules accept a className prop for every internal atom? Curious about what the others say

**Comment by Mohammer5** [comment]
I see that @HendrikThePendric already went for v3 in #472 
Referencing it here, because I don't know if this discussion has been resolved already

**Comment by varl** [comment]
>Using a prop is the easiest solution and will work well with non-responsive pages. Once we enter the responsiveness-territory this might be a bad solution, so I'm not sure which way to go.

Here's an option:

The form controls should be responsive by default, if a user overrides that behaviour with a fixed width, that's on them.

**Comment by Mohammer5** [comment]
Alright, sounds good to me

**Comment by HendrikThePendric** [comment]
Closing this issue because width has already been implemented on Input and TextArea:
- Input: https://github.com/dhis2/ui-core/pull/472/files#diff-5bedd40204b743fbc110882b24643de5R151-R155
- TextArea: https://github.com/dhis2/ui-core/pull/456/files#diff-4c338c77d4a04d0a255aed1cdbd6d513R142
