### ISSUE TITLE
SVG usage, padding, Material Icons

### ISSUE THREAD

**Issue by cooper-joe** [dhis2/ui-core#515]
Opening an issue to continue the discussion that started taking place on https://github.com/dhis2/ui-core/pull/514

The question: should we stick to using Material Design Icons, including padding, in components? Or, should we customize icons/SVG's for our own usage?

Relevant comments from the previous thread:

@Mohammer5:
> This is something that's bothering me for quite a while now. All our svgs contain some space around them, which makes it very hard to set the desired dimensions of the actual icon.
>
> I don't remember where we got this icon from, is there an online sketch file that we can "take apart" or does @cooper-joe have to give us the assets manually (if that's the case, I think we need to improve this workflow somehow for future components)

@cooper-joe:
> The Material Design icons from Google include the built-in padding around them. The reasoning is basically: 'the padding protects the icon from being placed too closed to the items around it'. We don't really need that kind of hand holding, so I'm happy to remove it. I worked a lot with @HendrikThePendric on this, so I'd like to get his input here too.
>
> I did in fact rebuild the SVG icons just yesterday for the radio and checkbox components. The files are included as resources in the design-system. (I included the padding for the regular sizes, but I can remove this if we will refactor.)
>
> The rebuilt SVGs:
>
>   - use only fill, never stroke, to allow for easier CSS color manipulation
>   - have meaningful, consistent layer names, to reduce required CSS rules and their complexity
>   - have removed unecessary groupings and translations
>   - and, they can have their padding removed.
>
> My opinion is that removing the padding would be a good idea, and that going forward I clean-up all SVG files before we use them in a component.

@HendrikThePendric:
> Why do our SVGs have padding and where do they come from
> Like @varl says: most are just being copied from Google's material-design-icons repo. But as @cooper-joe mentions, these Checkbox and Radio SVGs (plus the menu-arrow-icon) are now fully owned by us so, in theory, we can do whatever we like with them. However, if we decide to remove the padding from the regular (not dense) version of the Checkbox and Radio items, we sort of "lose compatibility" with the stock material-design-icons. And this has the unfortunate consequence that Joe will have to edit every icon we incorporate before it can be used. I don't think this is a good development.
>
>Please note:
>
>    In an ideal world I would also prefer to remove the padding from all these icons. That would be the nicest way to work for us developers.
>    But I just don't like the overhead this could produce

@ismay

> I would prefer to remove the padding from the icons as Joe suggested. The way I see it:

> - Removing the padding is a one-time operation
> - Our lib is separate from material-design-icons, though we import from them, my primary concern would be if what we're doing with our icons makes sense for us internally
> - The current approach is not as straightforward as just having icons without padding, dealing with that seems more time consuming to me than a one-time operation of modifying the icons

> I think the time we lose modifying the icons slightly, is offset by having a simpler approach to working with our icons.

**Comment by cooper-joe** [comment]
I think that removing padding and/or customizing the SVG icons should be limited to icons being used inside a component. Some examples:
- checkboxes
- radio buttons
- arrows for dropdowns
- sorting icons in table headers

This doesn't seem like too much overhead to me. I would also prefer to have control over how these icons are displayed, rather than trying to shim Material Icons into components.

An example where I have already done this: the menu arrow for the reworked menu. This icon does not have standard Material Icon padding, and using an icon with Material padding would not be compatible with the specs I've set. (The reason I reworked it: remove padding so we can use the same icon for regular and dense sizes).

To attempt to define a rule:
- icons that will never change in a component, and are not user editable, should be hand-built by Design Team.
- icons that are user-editable in a component should use Material Design icons, so that a user can easily drop their own ones in straight from the Material Icon Library.

**Comment by HendrikThePendric** [comment]
OK, lets' go for it!

Just thinking about what to do next:
- Since I've already worked on refactoring the Radio icons, I think I should also do the Checkbox icons.
- I don't think we need to merge branch https://github.com/dhis2/ui-core/pull/514 that @ismay worked on. Instead I'll just cherry-pick https://github.com/dhis2/ui-core/pull/514/commits/e98f744be0076f1e0e094e42139d6430e36eb3f1
- @cooper-joe needs to update the SVGs
- @cooper-joe needs to update the design specs for the non-padded icons, because I assume they will now need to be slightly smaller.

@cooper-joe @ismay you think that's a good way forward?

**Comment by Mohammer5** [comment]
Everything you guys have said so far sounds good to me

**Comment by ismay** [comment]
@HendrikThePendric Yes, sounds good to me as well 👍

**Comment by cooper-joe** [comment]
Sounds good, I'll let you know when those tasks from me are complete.

**Comment by HendrikThePendric** [comment]
I think most things mentioned in the issue have been addressed already. At least I know that the the padding has been removed from the SVGs used by the Checkbox, Radio and Switch. Perhaps the arrows and sorting icons still remain. If not, this issue can be closed. Could you provide an update @cooper-joe?

**Comment by cooper-joe** [comment]
This issue can be closed. The conclusion is still valid:
- icons that will never change in a component, and are not user editable, should be hand-built by Design Team.
- icons that are user-editable in a component should use Material Design icons, so that a user can easily drop their own ones in straight from the Material Icon Library.

Custom icons have been delivered and implemented for toggle controls and the select. Additional custom icons will be updated and tracked independent of this issue. (dropdown button arrow, table sorting)
