### ISSUE TITLE
Control Select width via props similarly to Input

### ISSUE THREAD

**Issue by edoardo** [dhis2/ui-core#586]
`InputField` (`Input`) component allow to control the input's width via the `inputWidth` (`width`) prop.
This works well when the `InputField` also has a help text (and/or label) wider than the input, as I can have a short input field without having to apply a width to a container element (defined in the app) which would cause the help text (and/or label) to wrap.

The `SingleSelectField` (and the other forms of Select) does not have a similar option.

**Comment by varl** [comment]
Resolved by 2d932cf in `next`.
