### ISSUE TITLE
Add min-width to input-type components

### ISSUE THREAD

**Issue by cooper-joe** [dhis2/ui-core#605]
As discussed here: https://github.com/dhis2/notes/pull/83, status icons reduce the width of the input. A min-width is applied to inputs to prevent them from become unusuble when a status is shown

`input` min-width: 72px (with status icon the input results in width of 44px)
`textarea` min width: 220px (with status icon the input results in width of 192px)
`select` (single and multi-) min-width: 100px (with status icon the input results in width of 72px)

**Comment by Mohammer5** [comment]
Should we be able to override this? I guess that inputs for max 1 or 2 digits could be smaller than 72px (especially if they need to be next to each other, e. g. `[day] - [month] - [year]`)

**Comment by cooper-joe** [comment]
72px is the minimum width where two digits can be displayed *and* there is room for a status icon. The following input is 72px (44px for the field, 4px margin, 24px icon)
![image](https://user-images.githubusercontent.com/33054985/69403775-c0d91c00-0cfb-11ea-86f1-f00eb00a3a88.png)

There are edge cases where a status icon would never be shown (or may be shown elsewhere). For the example you mentioned, a date input with 3 different inputs, that would certainly be useful to set min-widths, so perhaps it's worth having it exposed for our own sake, otherwise it may be difficult to always build with this component/atom.
