### ISSUE TITLE
Cypress helper visitStory is fragile

### ISSUE THREAD

**Issue by HendrikThePendric** [dhis2/ui-core#645]
I have found in ui-forms that the regex we are using to get the storybook id doesn't match the one being used by storybook internally. My specific problem was that the story name `Testing:Forms` would get the following IDs:
- Actual storybook iframe id `testing-forms`
- String produced by `visitStory` was `testingforms` (no dash)

Now... I think we are faced with a choice...
- Keep using this helper and just update the regex when we find a discrepancy with storybook (meh, I don't think reverse engineering this is a very solid approach)
- Stop using the helper completely, instead just use the ID from the URL (I'd prefer that to the first option)
- See if there is something exposed from storybook that can help us. (probably not)

What shall we do with this?

**Comment by HendrikThePendric** [comment]
I've had a look at the storybook repo, and I think this is the function that is producing the URLs:
https://github.com/storybookjs/storybook/blob/edb29bc91fb6a87d7f6a18a805044209943eecb0/lib/router/src/utils.ts#L17-L28
It seem to be exposed from the `@storybook/router` package. Will have a look.

**Comment by HendrikThePendric** [comment]
By now I managed to get this to work in ui-forms. Will prepare a PR for ui-core too.

**Comment by Mohammer5** [comment]
Oh, that's a very good solution you found there! Very nice!
