### ISSUE TITLE
Menu sublevels don't open on hover

### ISSUE THREAD

**Issue by edoardo** [dhis2/ui-core#782]
This can be verified also in storybook: https://ui-core.dhis2.nu/demo/?path=/story/menu--default.

The problem is caused by the CSS selector at https://github.com/dhis2/ui-core/blob/master/src/MenuItem.js#L28-L30:
`li:hover > div { display: block }`
which does not match any node in the current implementation.

<img width="1228" alt="Screenshot 2020-02-04 at 14 03 36" src="https://user-images.githubusercontent.com/150978/73747235-514dc700-4757-11ea-939b-7095c981311b.png">

the `li` node has a `span` node which contains the `div` that the CSS selector is intended to target.
(I manually changed `display` in the CSS to show the sublevel).

**Comment by HendrikThePendric** [comment]
Fixed
