### ISSUE TITLE
Issue with cosidering both {value,label} as an ID for selected field of UI components

### ISSUE THREAD

**Issue by chathurawidanage** [dhis2/ui-core#872]
In some UI components such as [MultiSelect](https://ui-core.dhis2.nu/demo/?path=/story/multiselect--default), both _value_ and _label_ should be passed into the selected field.

```jsx
<MultiSelect
  dataTest="dhis2-uicore-multiselect"
  onChange={function onChange(_ref2){var selected=_ref2.selected;alert("Selected changed to: ".concat(JSON.stringify(selected,null,2)))}}
  selected={[
    {
      label: 'one',
      value: '1'
    }
  ]}
>
```

This becomes problematic if the options of MultiSelect can be changed dynamically. 

Assume there are two components within the same UI. The first component can be used to define possible options for MultiSelects in the second component. A user defines some options in the first component and selects one of those options in the second component. Then the user goes back and changes just the text of one of the options(which has been already selected in MultiSelect). At this point, the selected field of MultiSelect holds something invalid and it breaks everything.

One possible workaround is generating a value => option{value, label} map and always update selected fields by looking up from this map. But if these UI components can be made to consider _value_ as the only ID, that will be much more convenient for the developers.

**Comment by ismay** [comment]
Hi @chathurawidanage, thanks for opening an issue. We're working on a new release here: https://github.com/dhis2/ui/pull/56, which implements using just the value for the `selected` prop.

I'll close this since it's been addressed, let me know if you have any questions!
